version: "3.8"

services:

  #Redis configuration
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - worker

  #Client configuration
  bull:
    build:
      context: ./
    env_file:
      - .env
    networks:
      - worker
    volumes:
      - ./build:/home/ubuntu/build
    command: yarn start:local
    depends_on:
      - redis

networks:
  worker:
    driver: bridge
