version: "3.8"

services:
# Zookeeper configuration
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - consumer

  # Kafka configuration
  kafka:
    image: confluentinc/cp-kafka:5.4.6
    networks:
      - consumer
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - zookeeper
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --list --bootstrap-server localhost:9092",
        ]
      interval: 20s
      timeout: 30s
      retries: 10

  #Consumer configuration
  consumer:
    build:
      context: .
      dockerfile: ./services/consumer/Dockerfile
    env_file:
      - ./services/consumer/.env
    networks:
      - consumer
    volumes:
      - ./services/consumer/build:/home/ubuntu/services/consumer/build
      - ./services/consumer/node_modules:/home/ubuntu/services/consumer/node_modules
    command: yarn workspace @event-boilerplate/consumer start:local
    depends_on:
      kafka:
        condition: service_healthy
      redis:

  #API configuration
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    env_file:
      - ./services/api/.env
    networks:
      - api
    volumes:
      - ./services/api/build:/home/ubuntu/services/api/build
      - ./services/api/node_modules:/home/ubuntu/services/api/node_modules
    command: yarn workspace @event-boilerplate/api start:local
    ports:
      - "4000:4000"
    depends_on:
      kafka:
        condition: service_healthy

  #Notification configuration
  socket:
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    env_file:
      - ./services/notification/.env
    networks:
      - socket
    volumes:
      - ./services/notification/build:/home/ubuntu/services/notification/build
      - ./services/notification/node_modules:/home/ubuntu/services/notification/node_modules
    command: yarn workspace @event-boilerplate/notification start:local
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  #Redis configuration
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - worker

  #Worker configuration
  bull:
    build:
      context: .
      dockerfile: ./services/worker/Dockerfile
    env_file:
      - ./services/worker/.env
    networks:
      - worker
    volumes:
      - ./services/worker/build:/home/ubuntu/services/worker/build
      - ./services/worker/node_modules:/home/ubuntu/services/worker/node_modules
    command: yarn workspace @event-boilerplate/worker start:local
    depends_on:
      - redis

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  api:
    driver: bridge
  consumer:
    driver: bridge
  socket:
    driver: bridge
  worker:
    driver: bridge