version: "3.8"

services:
  #Client configuration
  api:
    build:
      context: ./
    env_file:
      - .env
    networks:
      - api
    volumes:
      - ./build:/home/ubuntu/build
    command: yarn start:local
    ports:
      - "4000:4000"

networks:
  api:
    driver: bridge
